/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import config.KoneksiDB;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SYIFA AURELLIA
 */
public class FormSkripsiMahasiswa extends javax.swing.JFrame {

    /**
     * Creates new form FormSkripsiMahasiswa
     */
    
    private Statement st;
    private ResultSet rs;
    private Connection conn;
    private PreparedStatement pst;
    
    public FormSkripsiMahasiswa() {
        initComponents();
        conn = KoneksiDB.getKoneksi();
        tampilData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfNama = new javax.swing.JTextField();
        tfNim = new javax.swing.JTextField();
        tfDosenPembimbing = new javax.swing.JTextField();
        rbSedangDikerjakan = new javax.swing.JRadioButton();
        rbSelesai = new javax.swing.JRadioButton();
        cmbProdi = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        taProgressSkripsi = new javax.swing.JTextArea();
        tfJudulSkripsi = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_skripsi = new javax.swing.JTable();
        btnSubmit = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PENDATAAN SKRIPSI MAHASISWA UNIVERSITAS PELITA BANGSA - UAS SYIFA AURELLIA RAHMA");
        setBackground(new java.awt.Color(255, 51, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Pendataan Skripsi Mahasiswa");

        jLabel2.setText("Nama Mahasiswa :");

        jLabel3.setText("NIM :");

        jLabel4.setText("Dosen Pembimbing :");

        jLabel5.setText("Status");

        jLabel6.setText("Prodi :");

        jLabel7.setText("Judul Skripsi :");

        jLabel8.setText("Progress Skripsi :");

        tfNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNamaActionPerformed(evt);
            }
        });

        tfDosenPembimbing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDosenPembimbingActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbSedangDikerjakan);
        rbSedangDikerjakan.setText("Sedang Dikerjakan");
        rbSedangDikerjakan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSedangDikerjakanActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbSelesai);
        rbSelesai.setText("Selesai");
        rbSelesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSelesaiActionPerformed(evt);
            }
        });

        cmbProdi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Program Studi --", "Teknik Informatika", "Teknik Industri", "Teknik Sipil", "Teknik Lingkungan", "Teknik Arsitektur" }));
        cmbProdi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbProdiActionPerformed(evt);
            }
        });

        taProgressSkripsi.setColumns(20);
        taProgressSkripsi.setRows(5);
        jScrollPane1.setViewportView(taProgressSkripsi);

        tfJudulSkripsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfJudulSkripsiActionPerformed(evt);
            }
        });

        tbl_skripsi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_skripsi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_skripsiMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_skripsi);

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel2)
                        .addGap(112, 112, 112)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(tfNama, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(cmbProdi, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel3)
                        .addGap(181, 181, 181)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(tfNim, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(tfJudulSkripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(rbSedangDikerjakan)
                            .addComponent(rbSelesai, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfDosenPembimbing, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSubmit)
                .addGap(18, 18, 18)
                .addComponent(btnUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDelete)
                .addGap(173, 173, 173)
                .addComponent(btnClear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbProdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7))
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfNim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfJudulSkripsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfDosenPembimbing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbSedangDikerjakan))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)))
                        .addGap(1, 1, 1)
                        .addComponent(rbSelesai))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmit)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnClear)
                    .addComponent(btnExit))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
              if (tfNama.getText().equals("") || tfNim.getText().equals("") ||
        tfDosenPembimbing.getText().equals("") || tfJudulSkripsi.getText().equals("") ||
        taProgressSkripsi.getText().equals("") || buttonGroup1.getSelection() == null ||
        cmbProdi.getSelectedItem().equals("-- Program Studi --")) {
        
        JOptionPane.showMessageDialog(this, "Field harap diisi!", "Validasi", JOptionPane.ERROR_MESSAGE);
        return;
    }

    try {
        Connection conn = KoneksiDB.getKoneksi();
        Statement st = conn.createStatement();
        String status = rbSedangDikerjakan.isSelected() ? "Sedang Dikerjakan" : "Selesai";
        String sql = "INSERT INTO tbl_skripsi (nama, nim, prodi, judul_skripsi, dosen_pembimbing, progress_skripsi, status) VALUES ('" 
              + tfNama.getText() + "', '" 
              + tfNim.getText() + "', '" 
              + tfDosenPembimbing.getText() + "', '" 
              + status + "', '" 
              + cmbProdi.getSelectedItem() + "', '" 
              + tfJudulSkripsi.getText() + "', '" 
              + taProgressSkripsi.getText() + "')";

        st.executeUpdate(sql);
        JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
        tampilData();
        clearForm();
    } catch ( HeadlessException | SQLException e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
                                 
    }                       
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
         if (tbl_skripsi.getSelectedRow() == -1) {
        JOptionPane.showMessageDialog(this, "Pilih data yang ingin diupdate!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    try {
        String status = rbSedangDikerjakan.isSelected() ? "Sedang Dikerjakan" : "Selesai";
        String sql = "UPDATE tbl_skripsi SET nama=?, prodi=?, judul_skripsi=?, dosen_pembimbing=?, progress_skripsi=?, status=? WHERE nim=?";
        
        // Pastikan koneksi (conn) sudah terinisialisasi dan terbuka
        try (PreparedStatement pstmt = conn.prepareStatement(sql)) {
            pstmt.setString(1, tfNama.getText());
            pstmt.setString(2, tfDosenPembimbing.getText());
            pstmt.setString(3, status);
            pstmt.setString(4, (String) cmbProdi.getSelectedItem());
            pstmt.setString(5, tfJudulSkripsi.getText());
            pstmt.setString(6, taProgressSkripsi.getText());
            pstmt.setString(7, tfNim.getText());
            
            pstmt.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data berhasil diupdate");
            tampilData();
            clearForm();
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error SQL: " + e.getMessage());
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        hapusData();

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tbl_skripsiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_skripsiMouseClicked
        // TODO add your handling code here:
        int row = tbl_skripsi.getSelectedRow();
if (tbl_skripsi.getValueAt(row, 4).equals("Sedang Dikerjakan")) {
rbSedangDikerjakan.setSelected(true);
} else if (tbl_skripsi.getValueAt(row, 4).equals("Selesai")) {
rbSelesai.setSelected(true);
}
tfNama.setText(tbl_skripsi.getValueAt(row, 1).toString());
tfNim.setText(tbl_skripsi.getValueAt(row, 2).toString());
tfDosenPembimbing.setText(tbl_skripsi.getValueAt(row, 3).toString());
cmbProdi.setSelectedItem(tbl_skripsi.getValueAt(row, 5).toString());
tfJudulSkripsi.setText(tbl_skripsi.getValueAt(row, 6).toString());
taProgressSkripsi.setText(tbl_skripsi.getValueAt(row, 7).toString());
    }//GEN-LAST:event_tbl_skripsiMouseClicked

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
          tfNama.setText("");
    tfNim.setText("");
    tfDosenPembimbing.setText("");
    buttonGroup1.clearSelection(); // Mengosongkan pilihan radio button (jenis kelamin)
    cmbProdi.setSelectedIndex(0); // Mengembalikan ke pilihan awal untuk combo box
    tfJudulSkripsi.setText("");
    taProgressSkripsi.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
         int confirm = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin keluar?", "Konfirmasi Keluar", JOptionPane.YES_NO_OPTION);
    if (confirm == JOptionPane.YES_OPTION) {
        System.exit(0); // Keluar dari aplikasi
    }
    }//GEN-LAST:event_btnExitActionPerformed

    private void tfNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNamaActionPerformed

    private void tfJudulSkripsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfJudulSkripsiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfJudulSkripsiActionPerformed

    private void rbSelesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSelesaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbSelesaiActionPerformed

    private void cmbProdiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbProdiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbProdiActionPerformed

    private void tfDosenPembimbingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDosenPembimbingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDosenPembimbingActionPerformed

    private void rbSedangDikerjakanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSedangDikerjakanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbSedangDikerjakanActionPerformed

    
private void hapusData() {
int row = tbl_skripsi.getSelectedRow();
if (row == -1) {
JOptionPane.showMessageDialog(this, "Pilih baris yang akan di hapus !");
return;
}
int jawab = JOptionPane.showOptionDialog(this,
"Apakah Anda ingin menghapus data ini?",
"Konfirmasi",
JOptionPane.YES_NO_OPTION,
JOptionPane.QUESTION_MESSAGE, null, null, null);
if (jawab == JOptionPane.YES_OPTION) {
try {
String sql = "DELETE FROM tbl_skripsi WHERE nim='" +
tfNim.getText() + "' ";
pst = conn.prepareStatement(sql);
pst.executeUpdate();
JOptionPane.showMessageDialog(null, "Data berhasil di hapus");
clearForm();
tampilData();
} catch (Exception e) {
JOptionPane.showMessageDialog(this, e.getMessage());
}
} else {
clearForm();
tampilData();

}
}    
// Tambahkan method ini di akhir file atau sebelum method `main`
private void tampilData() {
    DefaultTableModel kolomtabel = new DefaultTableModel();
    kolomtabel.addColumn("No.");
    kolomtabel.addColumn("Nama");
    kolomtabel.addColumn("NIM");
    kolomtabel.addColumn("Prodi");
    kolomtabel.addColumn("Judul Skripsi");
    kolomtabel.addColumn("Dosen Pembimbing");
    kolomtabel.addColumn("Progress Skripsi");
    kolomtabel.addColumn("Status");

    try {
        Connection conn = KoneksiDB.getKoneksi();
        Statement st = conn.createStatement();
        String sql = "SELECT * FROM tbl_skripsi";
        ResultSet rs = st.executeQuery(sql);
        int nomor = 1;

        while (rs.next()) {
            kolomtabel.addRow(new Object[]{
                ("" + nomor++),
                rs.getString("nama"),
                rs.getString("nim"),
                rs.getString("prodi"),
                rs.getString("judul_skripsi"),
                rs.getString("dosen_pembimbing"),
                rs.getString("progress_skripsi"),
                rs.getString("status")
            });
        }
        tbl_skripsi.setModel(kolomtabel);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Gagal menampilkan data: " + e.getMessage());
    }
}

private void clearForm() {
    tfNama.setText("");
    tfNim.setText("");
    tfDosenPembimbing.setText("");
    buttonGroup1.clearSelection();
    cmbProdi.setSelectedIndex(0);
    tfJudulSkripsi.setText("");
    taProgressSkripsi.setText("");
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormSkripsiMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormSkripsiMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormSkripsiMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormSkripsiMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormSkripsiMahasiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbProdi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rbSedangDikerjakan;
    private javax.swing.JRadioButton rbSelesai;
    private javax.swing.JTextArea taProgressSkripsi;
    private javax.swing.JTable tbl_skripsi;
    private javax.swing.JTextField tfDosenPembimbing;
    private javax.swing.JTextField tfJudulSkripsi;
    private javax.swing.JTextField tfNama;
    private javax.swing.JTextField tfNim;
    // End of variables declaration//GEN-END:variables

}